import 'package:markup_common/markup_common.dart';

part 'markup_output.g.dart';

const _kSectionType = 'MarkupOutput';

/// Represents output block generated by a directive.  When reprocessing a
/// Markdown document, the first step is to strip all output blocks from the
/// document and then re-add the ones that were generated by that pass.
@JsonSerializable()
class MarkupOutput(
  super.content, {
  required super.end,
  super.sectionType = _kSectionType,
  required super.start,
  super.type = 'output',
}) extends MarkupBlock {
  factory fromJson(Map<String, dynamic> json) => _$MarkupOutputFromJson(json);

  factory fromSection(
    String content, {
    MarkupDirectiveOutput? output,
    required MarkdownSection section,
  }) {
    final result =
        '<!-- markup:output -->\n${_wrapOutput(content.trim(), output: output)}\n<!-- /markup:output -->\n';

    return MarkupOutput(
      result,
      end: section.start + 1 + result.split('\n').length,
      start: section.start + 1,
    );
  }

  static const kSectionType = _kSectionType;

  static String _wrapOutput(String content, {MarkupDirectiveOutput? output}) {
    var result = content;
    if (output != null) {
      final type = output.fenceType;
      final fence = output.fence ?? (type == null ? null : '```');

      if (fence != null) {
        result = '$fence${type ?? ''}\n$content\n$fence';
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() => _$MarkupOutputToJson(this);
}
