import 'package:markup_common/markup_common.dart';

part 'markup_output.g.dart';

const _kSectionType = 'MarkupOutput';

/// Represents output block generated by a directive.  When reprocessing a
/// Markdown document, the first step is to strip all output blocks from the
/// document and then re-add the ones that were generated by that pass.
@JsonSerializable()
class MarkupOutput(
  super.content, {
  required super.end,
  super.sectionType = _kSectionType,
  required super.start,
  super.type = 'output',
}) extends MarkupBlock {
  factory fromJson(Map<String, dynamic> json) => _$MarkupOutputFromJson(json);

  factory fromSection(String content, {required MarkdownSection section}) =>
      MarkupOutput(
        '<!-- markup:output -->\n${content.trim()}\n<!-- /markup:output -->\n',
        end: section.start + 1 + content.split('\n').length,
        start: section.start + 1,
      );

  static const kSectionType = _kSectionType;

  @override
  Map<String, dynamic> toJson() => _$MarkupOutputToJson(this);
}
