import 'package:markup_common/markup_common.dart';

/// Represents output block generated by a directive.  When reprocessing a
/// Markdown document, the first step is to strip all output blocks from the
/// document and then re-add the ones that were generated by that pass.
class MarkupOutput(
  super.content, {
  required super.end,
  required super.start,
  super.type = 'output',
}) extends MarkupBlock {
  factory fromSection(String content, {required MarkdownSection section}) =>
      MarkupOutput(
        '<!-- markup:output -->\n${content.trim()}\n<!-- /markup:output -->\n',
        end: section.start + 1 + content.split('\n').length,
        start: section.start + 1,
      );
}
