name: Tag & Publish (Mermaid)

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/publish_mermaid.yaml
      - packages/markup_mermaid/pubspec.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Validate
        shell: bash
        run: |
          set -e

          npm install -g @mermaid-js/mermaid-cli
          mmdc --help
          dart pub get
          dart format --set-exit-if-changed lib test
          dart run build_runner build
          dart analyze
          dart test
        working-directory: ./packages/markup_mermaid

      - name: Compile Binary
        run: |
          dart compile exe bin/markup_mermaid.dart -o bin/markup_mermaid
        working-directory: ./packages/markup_mermaid

      - name: Prepare Git
        shell: bash
        run: |
          set -e

          git config --global user.email "action@github.com"
          git config --global user.name "Github Action"

      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: bin
          path: outbin

      - name: Update Binary
        shell: bash
        run: |
          set -e

          mkdir -p outbin/linux/
          cp -f packages/markup_mermaid/bin/markup_mermaid outbin/linux/markup_mermaid
          chmod +x outbin/linux/markup_mermaid
          cd outbin
          git add .
          git commit --allow-empty -m "Update linux binary"
          git push

      # - name: Create Tag
      #   shell: bash
      #   run: |
      #     set -e

      #     dart pub global activate -sgit https://github.com/islandlifetechnologies/action-pubspec-tag
      #     dart pub global run dart_version_autotag:tag --token "${{ secrets.GITHUB_TOKEN }}"
      #   working-directory: ./packages/markup_mermaid

      # - name: Publish
      #   shell: bash
      #   run: |
      #     set -e

      #     set +e
      #     mkdir ~/.config
      #     mkdir ~/.config/dart

      #     set -e
      #     printf '${{ secrets.PUB_CREDENTIALS }}' > ~/.config/dart/pub-credentials.json

      #     dart pub publish --force
      #   working-directory: ./packages/markup_mermaid

  build_macos:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Prepare Git
        shell: bash
        run: |
          set -e

          git config set user.name "${{ github.actor }}"
          git config set user.email "${{ github.actor_email }}"

      - name: Compile Binary
        run: |
          dart compile exe bin/markup_mermaid.dart -o bin/markup_mermaid
        working-directory: ./packages/markup_mermaid

      - name: Prepare Git
        shell: bash
        run: |
          set -e

          git config --global user.email "action@github.com"
          git config --global user.name "Github Action"

      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          path: outbin
          ref: bin

      - name: Update Binary
        shell: bash
        run: |
          set -e

          mkdir -p outbin/macos/
          cp -f packages/markup_mermaid/bin/markup_mermaid outbin/macos/markup_mermaid
          chmod +x outbin/macos/markup_mermaid
          cd outbin
          git add .
          git commit --allow-empty -m "Update macos binary"
          git push

  bin_windows:
    needs: build_macos
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Prepare Git
        shell: bash
        run: |
          set -e

          git config --global user.email "action@github.com"
          git config --global user.name "Github Action"

      - name: Compile Binary
        run: |
          dart compile exe bin/markup_mermaid.dart -o bin/markup_mermaid.exe
        working-directory: ./packages/markup_mermaid

      - name: Prepare Git
        shell: bash
        run: |
          set -e

          git config set user.name "${{ github.actor }}"
          git config set user.email "${{ github.actor_email }}"

      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          path: outbin
          ref: bin

      - name: Update Binary
        shell: bash
        run: |
          set +e

          mkdir outbin/windows 2>nul
          set -e
          cp -f packages/markup_mermaid/bin/markup_mermaid.exe outbin/windows/markup_mermaid.exe
          chmod +x outbin/windows/markup_mermaid.exe
          cd outbin
          git add .
          git commit --allow-empty -m "Update windows binary"
          git push
