name: Tag & Publish (Markup)

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/publish.yaml
      - packages/markup/pubspec.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Validate
        shell: bash
        run: |
          set -e

          dart pub get
          dart format --set-exit-if-changed lib test
          dart run build_runner build
          dart analyze
          dart test
        working-directory: ./packages/markup

      - name: Compile Binary
        run: |
          dart compile exe bin/markup.dart -o bin/markup
        working-directory: ./packages/markup

      - name: Prepare Git
        shell: bash
        run: |
          set -e

          git config set user.name "${{ github.actor }}"
          git config set user.email "${{ github.actor_email }}"

      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: bin
          path: outbin

      - name: Update Binary
        shell: bash
        run: |
          set -e

          mkdir -p outbin/linux/
          cp -f packages/markup/bin/markup outbin/linux/markup
          chmod +x outbin/linux/markup
          cd outbin
          git add .
          git commit -m "Update linux binary"
          git push

      # - name: Create Tag
      #   shell: bash
      #   run: |
      #     set -e

      #     dart pub global activate -sgit https://github.com/islandlifetechnologies/action-pubspec-tag
      #     dart pub global run dart_version_autotag:tag --token "${{ secrets.GITHUB_TOKEN }}"
      #   working-directory: ./packages/markup

      # - name: Publish
      #   shell: bash
      #   run: |
      #     set -e

      #     set +e
      #     mkdir ~/.config
      #     mkdir ~/.config/dart

      #     set -e
      #     printf '${{ secrets.PUB_CREDENTIALS }}' > ~/.config/dart/pub-credentials.json

      #     dart pub publish --force
      #   working-directory: ./packages/markup

  build_macos:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Prepare Git
        shell: bash
        run: |
          set -e

          git config set user.name "${{ github.actor }}"
          git config set user.email "${{ github.actor_email }}"

      - name: Compile Binary
        run: |
          dart compile exe bin/markup.dart -o bin/markup
        working-directory: ./packages/markup

      - name: Prepare Git
        shell: bash
        run: |
          set -e

          git config set user.name "${{ github.actor }}"
          git config set user.email "${{ github.actor_email }}"

      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          path: outbin
          ref: bin

      - name: Update Binary
        shell: bash
        run: |
          set -e

          mkdir -p outbin/macos/
          cp -f packages/markup/bin/markup outbin/macos/markup
          chmod +x outbin/macos/markup
          cd outbin
          git add .
          git commit -m "Update macos binary"
          git push

  bin_windows:
    needs: build_macos
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Prepare Git
        shell: bash
        run: |
          set -e

          git config set user.name "${{ github.actor }}"
          git config set user.email "${{ github.actor_email }}"

      - name: Compile Binary
        run: |
          dart compile exe bin/markup.dart -o bin/markup.exe
        working-directory: ./packages/markup

      - name: Prepare Git
        shell: bash
        run: |
          set -e

          git config set user.name "${{ github.actor }}"
          git config set user.email "${{ github.actor_email }}"

      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          path: outbin
          ref: bin

      - name: Update Binary
        shell: bash
        run: |
          set -e

          if not exist "outbin\windows" mkdir "outbin\windows"
          cp -f packages\markup\bin\markup.exe outbin\windows\markup.exe
          chmod +x outbin\windows\markup.exe
          cd outbin
          git add .
          git commit -m "Update windows binary"
          git push
