name: Test

on:
  workflow_dispatch:
  push:
    branches: [bin]

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          ref: bin
          path: bin

      - shell: bash
        run: |
          bin/linux/markup --help
          bin/linux/markup_mermaid --help

  test-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v7
        with:
          ref: bin
          path: bin

      - shell: bash
        run: |
          bin/macos/markup --help
          bin/macos/markup_mermaid --help

  test-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7
        with:
          ref: bin
          path: bin

      - shell: bash
        run: |
          bin/windows/markup --help
          bin/windows/markup_mermaid --help
